steps:

- name: 'bash'
  id: 'Delete ancillary docker-compose files'
  args: ['rm', 'docker-compose.override.yml']

# - name: 'bash'
#   id: 'load env vars'
#   args:
#   - '-c'
#   - |
#     cat vars/build/default.env >> /workspace/.env
#     cat vars/build/prod.env >> /workspace/.env

- name: 'docker'
  id: 'Build test image'
  args: ['compose', 'build', 'workflow-tests']

# - name: 'docker'
#   id: 'Build test image'
#   entrypoint: 'bash'
#   args:
#   - '-c'
#   - |
#     source /workspace/.env
#     docker compose build workflow-tests

- name: 'gcr.io/cloud-builders/docker'
  id: 'Run tests'
  args: ['compose', 'run', 'workflow-tests']

# - name: 'gcr.io/cloud-builders/docker'
#   id: 'build test image'
#   # args: ['build', '-t', 'workflow-tests', '--target', 'workflow-tests', '.']
#   args: ['compose*', 'build', 'workflow-tests']
#   # entrypoint: 'bash'
#   # args:
#   # - '-c'
#   # - |
#   #   source vars/build/default.env
#   #   source vars/build/prod.env
#   #   ENV=$$ENV IMAGE_REGISTRY=$$IMAGE_REGISTRY docker build workflow-tests

# - name: 'gcr.io/cloud-builders/docker'
#   id: 'run tests'
#   args: ['run', 'workflow-tests']

# STAGES
