steps:

- name: 'bash'
  id: 'Delete ancillary docker-compose files'
  args: ['rm', 'docker-compose.override.yml']

- name: 'docker'
  id: 'Build test image'
  args: ['compose', 'build', 'workflow-tests']
  env:
    - 'ENV=prod'

- name: 'docker'
  id: 'Run tests'
  args: ['compose', 'run', 'workflow-tests']
  env:
    - 'ENV=prod'

- name: 'gcr.io/cloud-builders/docker'
  id: "Tag test image"
  args: ['tag', 'workflow-tests:latest' ,'gcr.io/$PROJECT_ID/workflow-tests']

images:
  - 'gcr.io/$PROJECT_ID/workflow-tests:latest'

# - name: 'docker'
#   id: 'Tag and push test image'
#   entrypoint: 'bash'
#   args:
#   - '-c'
#   - |
#     docker tag $$IMAGE_REGISTRY/workflow-tests:$$DOCKER_TAG $$IMAGE_REGISTRY/workflow-tests:latest

# - name: 'gcr.io/cloud-builders/docker'
#   id: 'build test image'
#   # args: ['build', '-t', 'workflow-tests', '--target', 'workflow-tests', '.']
#   args: ['compose*', 'build', 'workflow-tests']
#   # entrypoint: 'bash'
#   # args:
#   # - '-c'
#   # - |
#   #   source vars/build/default.env
#   #   source vars/build/prod.env
#   #   ENV=$$ENV IMAGE_REGISTRY=$$IMAGE_REGISTRY docker build workflow-tests

# - name: 'gcr.io/cloud-builders/docker'
#   id: 'run tests'
#   args: ['run', 'workflow-tests']

# STAGES
