steps:

# Stage 1: Preparation
- name: 'bash'
  id: 'Delete ancillary docker-compose files'
  args: ['rm', 'docker-compose.override.yml']

# Stage 2: Build production image
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build prod image'
  args: ['compose', 'build', 'workflow']
  env:
    - 'DOCKER_BUILDKIT=1'
    - 'ENV=prod'
    - 'IMAGE_REGISTRY=gcr.io/$PROJECT_ID'
    - 'CACHE_TAG=$BRANCH_NAME.$SHORT_SHA'

# Stage 3: Tag production image
- name: 'gcr.io/cloud-builders/docker'
  id: "Tag prod image"
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    docker tag workspace_workflow:latest gcr.io/$PROJECT_ID/workflow:$$CACHE_TAG
    docker tag workspace_workflow:latest gcr.io/$PROJECT_ID/workflow
  env:
    - 'CACHE_TAG=$BRANCH_NAME.$SHORT_SHA'

# Stage 4: Inject tag into DAG manifest and copy to GCS bucket
- name: 'gcr.io/cloud-builders/gsutil'
  id: 'Inject image tag into the DAG manifest'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    sed -i "s/docker_tag_placeholder/$$CACHE_TAG/g" dag-manifest.yaml
    gsutil cp dag-manifest.yaml $$GCS_BUCKET/$$DAG_MANIFEST_PATH
  env:
    - 'CACHE_TAG=$BRANCH_NAME.$SHORT_SHA'
    - 'GCS_BUCKET=gs://madecom-dev-alex-gregory-sandbox'
    - 'DAG_MANIFEST_PATH=dags/workflow.yaml'

# Push images created in this CI/CD pipeline
images:
  - 'gcr.io/$PROJECT_ID/workflow'
