steps:

# Preparation Stage
- name: 'bash'
  id: 'Delete ancillary docker-compose files'
  args: ['rm', 'docker-compose.override.yml']

# Build workflow-test image
- name: 'gcr.io/cloud-builders/docker'
# - name: 'docker'
  id: 'Build test image'
  args: ['compose', 'build', 'workflow-tests']
  env:
    - 'DOCKER_BUILDKIT=1'
    - 'ENV=prod'
    - 'IMAGE_REGISTRY=gcr.io/$PROJECT_ID'
    - 'CACHE_TAG=$BRANCH_NAME.$SHORT_SHA'

# Run workflow-tests image
- name: 'gcr.io/cloud-builders/docker'
# - name: 'docker'
  id: 'Run tests'
  args: ['compose', 'run', 'workflow-tests']
  env:
    - 'ENV=prod'

# Tag workflow image
- name: 'gcr.io/cloud-builders/docker'
# - name: 'docker'
  id: "Tag prod image"
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    docker tag workspace_workflow:latest gcr.io/$PROJECT_ID/workflow:$$CACHE_TAG
    docker tag workspace_workflow:latest gcr.io/$PROJECT_ID/workflow
  # args: ['tag', 'workspace_workflow:latest', 'gcr.io/$PROJECT_ID/workflow:$$CACHE_TAG']
  env:
    - 'CACHE_TAG=$BRANCH_NAME.$SHORT_SHA'

# Tag workflow-test image
- name: 'gcr.io/cloud-builders/docker'
# - name: 'docker'
  id: "Tag test image"
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    docker tag workspace_workflow-tests:latest gcr.io/$PROJECT_ID/workflow:$$CACHE_TAG
    docker tag workspace_workflow-tests:latest gcr.io/$PROJECT_ID/workflow
  # args: ['tag', 'workspace_workflow-tests:latest', 'gcr.io/$PROJECT_ID/workflow-tests:$$CACHE_TAG']
  env:
    - 'CACHE_TAG=$BRANCH_NAME.$SHORT_SHA'

# If builds in list below are successful in previous stages, this implicitly pushes them to GCR
# want to see if this pushes just the latest or all
images:
  - 'gcr.io/$PROJECT_ID/workflow'
  - 'gcr.io/$PROJECT_ID/workflow-tests'
