version: '3.8'

services:

  workflow:
    build:
      context: .
      dockerfile: Dockerfile
      target: workflow
      args:
        - BUILDKIT_INLINE_CACHE=1
      cache_from:
        # - ${IMAGE_REGISTRY}/workflow:${CACHE_TAG}  # GCR latest build related to a branch?
        - ${IMAGE_REGISTRY}/workflow:latest  # GCR latest build prod image
    env_file:
      - ./vars/env/default.env
      - ./vars/env/${ENV}.env  # shell env var
    volumes:
      - ./access_token.json:/code/access_token.json

  workflow-tests:
    build:
      context: .
      dockerfile: Dockerfile
      target: workflow-tests
      args:
        - BUILDKIT_INLINE_CACHE=1
      cache_from:
        # - ${IMAGE_REGISTRY}/workflow-tests:${CACHE_TAG}  # GCR latest build related to a branch?
        - ${IMAGE_REGISTRY}/workflow-tests:latest  # GCR latest build test image
        - ${IMAGE_REGISTRY}/workflow:latest  # GCR latest build image
    depends_on:
      - workflow
    env_file:
      - ./vars/env/default.env
      - ./vars/env/${ENV}.env
    volumes:
      - ./access_token.json:/code/access_token.json
