version: '3.8'

services:

  workflow:
    build:
      context: .
      dockerfile: Dockerfile
      target: workflow

  workflow-tests:
    build:
      context: .
      dockerfile: Dockerfile
      target: workflow-tests
    depends_on:
      - workflow
